import { test, expect } from "@playwright/test";
import { getEnv, httpCredentials, TEST_AGENT } from "./_helpers.js";

const env = getEnv();

test.use({
  httpCredentials: httpCredentials(env),
});

/**
 * The dashboard renders the Close Question Prompt field only for agents that
 * already have a Close Question node in their canonical JSON. Brand-new
 * builds get one automatically (the generator emits the four-node chain);
 * agents older than this phase will populate the field on their next
 * save-and-publish (the editor lazily adds the node into the JSON).
 *
 * This smoke test only verifies the dashboard wires up the field correctly
 * when the API includes `closeQuestionPrompt`. the test agent in production
 * may or may not have been regenerated by the time this test runs, so the
 * presence-on-fixture check is conditional via test.skip.
 */
test.describe("Close Question Prompt — dashboard field", () => {
  test("the field is rendered + readable when the agent has a Close Question node", async ({ page }) => {
    await page.goto("/dashboard");
    const row = page.locator(`#agentList [data-slug="${TEST_AGENT.slug}"]`);
    await expect(row).toBeVisible({ timeout: 15_000 });
    await row.click();

    await expect(page.locator("#detailView")).toBeVisible({ timeout: 15_000 });

    // Open the Node Editor (where closing prompts surface).
    await page.locator('button.agent-tab[data-tab="nodes"]').click();
    await expect(page.locator("#nodeEditorContainer")).toBeVisible({ timeout: 15_000 });

    // Look for the "Close Question Prompt" label rendered by fieldBlock().
    const label = page.getByText("Close Question Prompt", { exact: true });
    const hasField = (await label.count()) > 0;
    test.skip(
      !hasField,
      "the test agent not yet regenerated with the Close Question node — field absent (expected on older agents)",
    );

    await expect(label.first()).toBeVisible();
  });
});
